[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "master"

[[constraint]]
    name = "github.com/globalsign/mgo"
    revision = "r2018.04.03"

[prune]
  go-tests = true
  unused-packages = true
